In [12]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
d=pd.read_csv("BIKE_DETAILS[1].csv")
print(d)

                                     name  selling_price  year seller_type  \
0               Royal Enfield Classic 350         175000  2019  Individual
1                               Honda Dio          45000  2017  Individual
2     Royal Enfield Classic Gunmetal Grey         150000  2018  Individual
3       Yamaha Fazer FI V 2.0 [2016-2018]          65000  2015  Individual
4                   Yamaha SZ [2013-2014]          20000  2011  Individual
...                                   ...            ...   ...         ...
1056                            Activa 3g          17000  2010  Individual
1057                     Honda CB twister          16000  2012  Individual
1058                   Bajaj Discover 125          15000  2013  Individual
1059                       Honda CB Shine          12000  2009  Individual
1060                     Bajaj Pulsar 150          10000  2008  Individual

          owner  km_driven  ex_showroom_price
0     1st owner        350                NaN
1     1st owner       5650                NaN
2     1st owner      12000           148114.0
3     1st owner      23000            89643.0
4     2nd owner      21000                NaN
...         ...        ...                ...
1056  1st owner     500000            52000.0
1057  1st owner      33000            51000.0
1058  2nd owner      35000            57000.0
1059  1st owner      53000            58000.0
1060  1st owner      92233            75000.0

[1061 rows x 7 columns]

In [13]:
df=d.dropna()
df

,name,selling_price,year,seller_type,owner,km_driven,ex_showroom_price
2,Royal Enfield Classic Gunmetal Grey,150000,2018,Individual,1st owner,12000,148114.0
3,Yamaha Fazer FI V 2.0 [2016-2018],65000,2015,Individual,1st owner,23000,89643.0
5,Honda CB Twister,18000,2010,Individual,1st owner,60000,53857.0
6,Honda CB Hornet 160R,78500,2018,Individual,1st owner,17000,87719.0
9,Bajaj Discover 125,50000,2016,Individual,1st owner,42000,60122.0
...,...,...,...,...,...,...,...
1056,Activa 3g,17000,2010,Individual,1st owner,500000,52000.0
1057,Honda CB twister,16000,2012,Individual,1st owner,33000,51000.0
1058,Bajaj Discover 125,15000,2013,Individual,2nd owner,35000,57000.0
1059,Honda CB Shine,12000,2009,Individual,1st owner,53000,58000.0
1060,Bajaj Pulsar 150,10000,2008,Individual,1st owner,92233,75000.0

In [14]:
df.drop_duplicates()
df

,name,selling_price,year,seller_type,owner,km_driven,ex_showroom_price
2,Royal Enfield Classic Gunmetal Grey,150000,2018,Individual,1st owner,12000,148114.0
3,Yamaha Fazer FI V 2.0 [2016-2018],65000,2015,Individual,1st owner,23000,89643.0
5,Honda CB Twister,18000,2010,Individual,1st owner,60000,53857.0
6,Honda CB Hornet 160R,78500,2018,Individual,1st owner,17000,87719.0
9,Bajaj Discover 125,50000,2016,Individual,1st owner,42000,60122.0
...,...,...,...,...,...,...,...
1056,Activa 3g,17000,2010,Individual,1st owner,500000,52000.0
1057,Honda CB twister,16000,2012,Individual,1st owner,33000,51000.0
1058,Bajaj Discover 125,15000,2013,Individual,2nd owner,35000,57000.0
1059,Honda CB Shine,12000,2009,Individual,1st owner,53000,58000.0
1060,Bajaj Pulsar 150,10000,2008,Individual,1st owner,92233,75000.0

In [15]:
le = LabelEncoder()
df["owner"] = le.fit_transform(df["owner"])

C:\Users\rprem\AppData\Local\Temp\ipykernel_12676\3577773294.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["owner"] = le.fit_transform(df["owner"])

In [16]:
X = df[["year", "km_driven", "owner"]]
y = df["selling_price"]

In [18]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)

# 
sample = [[2019, 350, 1]]   # 0 = encoded va
prediction = model.predict(sample)

print("Predicted Price of the bike:", prediction[0])

Predicted Price of the bike: 109363.11047571711

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(